// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPEGOJj-YmRWVzIlpt0aGQkGmTKeWEofM',
    appId: '1:663229103692:web:bf94e6e79d51bba1c9bee9',
    messagingSenderId: '663229103692',
    projectId: 'wscube-39aaf',
    authDomain: 'wscube-39aaf.firebaseapp.com',
    storageBucket: 'wscube-39aaf.appspot.com',
    measurementId: 'G-W03ML1MXE5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJ5hR2z0HvihfdJO-xKKAdjuM5kREEwsI',
    appId: '1:663229103692:android:54415681e008f77bc9bee9',
    messagingSenderId: '663229103692',
    projectId: 'wscube-39aaf',
    storageBucket: 'wscube-39aaf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3NkKjUwRwDW_D5hebkxmFQtba57mmyVw',
    appId: '1:663229103692:ios:1f777866e3c0aa2fc9bee9',
    messagingSenderId: '663229103692',
    projectId: 'wscube-39aaf',
    storageBucket: 'wscube-39aaf.appspot.com',
    iosBundleId: 'com.example.wscubeFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3NkKjUwRwDW_D5hebkxmFQtba57mmyVw',
    appId: '1:663229103692:ios:09fb2255a3f53eadc9bee9',
    messagingSenderId: '663229103692',
    projectId: 'wscube-39aaf',
    storageBucket: 'wscube-39aaf.appspot.com',
    iosBundleId: 'com.example.wscubeFirebase.RunnerTests',
  );
}
